[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'Shougo/neomru.vim'
depends = ['unite']

[[plugins]]
repo = 'Shougo/neoyank.vim'
depends = ['unite']

[[plugins]]
repo = 'Shougo/unite-outline'
depends = ['unite']

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kassio/neoterm'
if = "has('nvim')"

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'jceb/vim-hier'
